/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZVBVM1lESzNaY1dqQ1AxcVBINEJRMFFZT0JQdFBibGhqb0FXdVJVZTBFOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQXE5cEpUZVB0c3VMTUY4QzNKVHdIdE1MTHJvVDlZZWF6TStydHgzOWp5ST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTQVVIOVlwaVA5V1psbkxUcVNuaEVVTzZmTkdkbG5pMUlBZjlvdHlCb0ZBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJmVDZQTU9rNldSUlVFZlBQL2htdU1qeUdiT0JaVHROaGhuYmV1RXM2ZWdRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitLU2hWVC9KTGNJa3NYVjBHMHAvdVZoL2NNWnVZMVloSy9vTi95UDFMbVE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRxb3NXSUgyWC8wZUp0LzBuUDdMajJTcWlYR2tNQmRTczJGKzFaM2VzQ0U9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkhzSVhxa1pTcEdPZExMMWVweU5QNW5OZmtKYmQwRFVFd3lNMnI3ZVFYcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoielBZQTdvdGgrYzFHWnB0M0hzaXdqMmw1V3Q2amlyYnZ6THErVitJbW8wMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJ1eEZUMTFUSk9kUGpHajRvNlNlS09HeG5pUWR2dzQxZWZXV3ZSS3JOMnVFYkc4dktac0V4dlNCV3o5R25WN2FXT3VUZTZuYVZ2bzNNUU00YkN4dmhRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTAsImFkdlNlY3JldEtleSI6IkU1ZHFZejdPdlErSktvYXp3bzhsKzdjT3JhOUxPUk4wUG94OEVIZTFGeWM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjo2MSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjYxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Ilc1T3ZsaGxSUWFtQVF0M1B6WXdVMEEiLCJwaG9uZUlkIjoiNDg4ZmM4M2YtMTVlYy00YWMyLTg0NzAtZTVlOGMyNGRkYTY5IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhZd2dDS0JJZmN2ZnhodnhWd01jUUFjTkNWST0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJWell3bnc3ZFNqYm43MEh4Vk8vTk5lWGdaMWc9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiRkdSSDNMVkgiLCJtZSI6eyJpZCI6IjIzNDgwNTAzNDcyMjQ6MTVAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xPTm5hQUdFTGFEb2JrR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlhTUnFjdG1zTUVUWjJqa1NSUDNYWkdmdGZDWXZzYXZ5UU1nNkEyUDZ0Z1U9IiwiYWNjb3VudFNpZ25hdHVyZSI6IktBVmpKdGY3UkczQzN5Q0JEdzJoaU1CdXBKdXMzd3VQdGZMb2t2cFJlU0plbTRsY2c2UVdrTUlpTjhHeG5GdXUzVmhRYTIwWEx3MnAvbmpNaWhkVEFBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJxYUQwVnFRSzd6c3pTSTZsOVpva0g1SWpGNFZOeFZ6T1hjZ2lvakVobC9QTWFiU2diVGNGdXdNbkkzRUxqNFJkSHY5Q3JwUTJRaXpXY2tVWmN1bnJnQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDgwNTAzNDcyMjQ6MTVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVjBrYW5MWnJEQkUyZG81RWtUOTEyUm43WHdtTDdHcjhrRElPZ05qK3JZRiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMDY5MTUyMywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFDeHgifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '2348050347224';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
